---
- hosts: mongodb 
  become: true 
  tasks: 
    - name: download maven 
      get_url: 
        url: http://mirrors.estointernet.in/apache/maven/maven-3/3.6.2/binaries/apache-maven-3.6.2-bin.tar.gz
        dest: /opt/
    - name: untar the file
      unarchive: 
        src: /opt/apache-maven-3.6.2-bin.tar.gz
        dest: /opt/
        remote_src: yes
    - name: remove untar file
      file:
        path: /opt/apache-maven-3.6.2-bin.tar.gz
        state: absent
        

    