---
- hosts: mongodb 
  become: true 
  tasks: 
    - name: install docker 
      yum: 
        name: docker 
        state: present 
    - name: start and enable 
      service: 
        name: docker 
        state: started 
        enabled: true
    - name: install pip
      yum: 
        name: python-pip 
        state: present 
    - name: install docker-py 
      yum: 
        name: docker-py 
        state: present  
    - name: create mongodb container 
      docker_container: 
        name: mongo
        tag: mongo:latest