---
- hosts: mongodb 
  become: true 
  tasks: 
    - name: install docker 
      yum: 
        name: docker 
        state: present 
    - name: start and enable 
      service: 
        name: docker 
        state: started 
        enabled: true 
    - name: create mongodb container 
      docker_container: 
        image: mongo
        tag: latest